window.CM2_VOCABULARY = [
  {
    "word": "autonomie",
    "nature": "nom féminin",
    "definition": "Capacité à agir et à s’organiser sans aide constante.",
    "example": "Je prépare mon cartable avec autonomie.",
    "feminine": "",
    "plural": "autonomies",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "consigne",
    "nature": "nom féminin",
    "definition": "Instruction qui explique le travail à faire.",
    "example": "Je lis la consigne avant de répondre.",
    "feminine": "",
    "plural": "consignes",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "hypothèse",
    "nature": "nom féminin",
    "definition": "Explication possible que l’on doit vérifier.",
    "example": "Nous testons notre hypothèse.",
    "feminine": "",
    "plural": "hypothèses",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "argument",
    "nature": "nom masculin",
    "definition": "Raison utilisée pour justifier une idée.",
    "example": "Je donne un argument précis.",
    "feminine": "",
    "plural": "arguments",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "conclusion",
    "nature": "nom féminin",
    "definition": "Idée finale tirée d’un raisonnement.",
    "example": "La conclusion répond à la question.",
    "feminine": "",
    "plural": "conclusions",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "conséquence",
    "nature": "nom féminin",
    "definition": "Résultat produit par une action ou un événement.",
    "example": "La pluie a pour conséquence une route mouillée.",
    "feminine": "",
    "plural": "conséquences",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "comparaison",
    "nature": "nom féminin",
    "definition": "Observation des ressemblances et des différences.",
    "example": "La comparaison de ces textes est utile.",
    "feminine": "",
    "plural": "comparaisons",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "expérience",
    "nature": "nom féminin",
    "definition": "Essai réalisé pour observer un phénomène.",
    "example": "Nous réalisons une expérience sur l’eau.",
    "feminine": "",
    "plural": "expériences",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "observation",
    "nature": "nom féminin",
    "definition": "Examen attentif de quelque chose.",
    "example": "Cette observation confirme notre idée.",
    "feminine": "",
    "plural": "observations",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "précision",
    "nature": "nom féminin",
    "definition": "Qualité de ce qui est exact et bien détaillé.",
    "example": "Je trace ce cercle avec précision.",
    "feminine": "",
    "plural": "précisions",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "proportion",
    "nature": "nom féminin",
    "definition": "Rapport entre une quantité et un ensemble.",
    "example": "La proportion de billes rouges est faible.",
    "feminine": "",
    "plural": "proportions",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "fraction",
    "nature": "nom féminin",
    "definition": "Nombre qui représente une ou plusieurs parts égales d’une unité.",
    "example": "Un demi est une fraction.",
    "feminine": "",
    "plural": "fractions",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "périmètre",
    "nature": "nom masculin",
    "definition": "Longueur du contour d’une figure.",
    "example": "Je calcule le périmètre du carré.",
    "feminine": "",
    "plural": "périmètres",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "surface",
    "nature": "nom féminin",
    "definition": "Partie qui forme l’extérieur d’un objet ou une étendue plane.",
    "example": "La surface de la table est lisse.",
    "feminine": "",
    "plural": "surfaces",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "angle",
    "nature": "nom masculin",
    "definition": "Ouverture formée par deux demi-droites de même origine.",
    "example": "Un angle droit mesure quatre-vingt-dix degrés.",
    "feminine": "",
    "plural": "angles",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "ressource",
    "nature": "nom féminin",
    "definition": "Moyen ou richesse que l’on peut utiliser.",
    "example": "L’eau est une ressource précieuse.",
    "feminine": "",
    "plural": "ressources",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "citoyen",
    "nature": "nom masculin",
    "definition": "Personne qui possède des droits et des devoirs dans un pays.",
    "example": "Chaque citoyen doit respecter les lois.",
    "feminine": "citoyenne",
    "plural": "citoyens",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "égalité",
    "nature": "nom féminin",
    "definition": "Fait d’avoir la même valeur ou les mêmes droits.",
    "example": "L’égalité est une valeur de la République.",
    "feminine": "",
    "plural": "égalités",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "liberté",
    "nature": "nom féminin",
    "definition": "Possibilité d’agir dans le respect des droits des autres.",
    "example": "La liberté d’expression permet de donner son avis.",
    "feminine": "",
    "plural": "libertés",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "solidarité",
    "nature": "nom féminin",
    "definition": "Entraide entre des personnes.",
    "example": "La solidarité nous aide à surmonter les difficultés.",
    "feminine": "",
    "plural": "solidarités",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "récit",
    "nature": "nom masculin",
    "definition": "Texte qui raconte des événements.",
    "example": "Ce récit raconte une aventure.",
    "feminine": "",
    "plural": "récits",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "personnage",
    "nature": "nom masculin",
    "definition": "Être qui joue un rôle dans une histoire.",
    "example": "Le personnage principal cherche son chemin.",
    "feminine": "",
    "plural": "personnages",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "narrateur",
    "nature": "nom masculin",
    "definition": "Voix qui raconte une histoire.",
    "example": "Le narrateur décrit la forêt.",
    "feminine": "narratrice",
    "plural": "narrateurs",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "portrait",
    "nature": "nom masculin",
    "definition": "Description ou représentation d’une personne.",
    "example": "L’auteur fait le portrait du héros.",
    "feminine": "",
    "plural": "portraits",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "synonyme",
    "nature": "nom masculin",
    "definition": "Mot dont le sens est proche de celui d’un autre.",
    "example": "Rapide est un synonyme de véloce.",
    "feminine": "",
    "plural": "synonymes",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "contraire",
    "nature": "nom masculin",
    "definition": "Mot ou idée dont le sens est opposé à un autre.",
    "example": "Le contraire de chaud est froid.",
    "feminine": "",
    "plural": "contraires",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "préfixe",
    "nature": "nom masculin",
    "definition": "Élément placé devant un mot pour en modifier le sens.",
    "example": "Dans refaire, re- est un préfixe.",
    "feminine": "",
    "plural": "préfixes",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "suffixe",
    "nature": "nom masculin",
    "definition": "Élément ajouté à la fin d’un radical.",
    "example": "Dans rapidement, -ment est un suffixe.",
    "feminine": "",
    "plural": "suffixes",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "précis",
    "nature": "adjectif",
    "definition": "Qui donne des détails exacts.",
    "example": "Il donne une réponse précise.",
    "feminine": "précise",
    "plural": "précis",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "attentif",
    "nature": "adjectif",
    "definition": "Qui écoute ou observe avec soin.",
    "example": "Une élève attentive lit la consigne.",
    "feminine": "attentive",
    "plural": "attentifs",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "curieux",
    "nature": "adjectif",
    "definition": "Qui a envie de découvrir et de comprendre.",
    "example": "Les enfants curieux posent des questions.",
    "feminine": "curieuse",
    "plural": "curieux",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "heureux",
    "nature": "adjectif",
    "definition": "Qui ressent de la joie.",
    "example": "Elle est heureuse de réussir.",
    "feminine": "heureuse",
    "plural": "heureux",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "courageux",
    "nature": "adjectif",
    "definition": "Qui agit malgré la peur ou la difficulté.",
    "example": "Cette fille courageuse aide son ami.",
    "feminine": "courageuse",
    "plural": "courageux",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "respectueux",
    "nature": "adjectif",
    "definition": "Qui montre du respect.",
    "example": "Un élève respectueux écoute les autres.",
    "feminine": "respectueuse",
    "plural": "respectueux",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "naturel",
    "nature": "adjectif",
    "definition": "Qui vient de la nature.",
    "example": "Cette forêt est un milieu naturel.",
    "feminine": "naturelle",
    "plural": "naturels",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "essentiel",
    "nature": "adjectif",
    "definition": "Qui est absolument nécessaire ou très important.",
    "example": "L’eau est essentielle à la vie.",
    "feminine": "essentielle",
    "plural": "essentiels",
    "tense": "",
    "conjugation": "",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "observer",
    "nature": "verbe",
    "definition": "Regarder avec attention pour comprendre.",
    "example": "Nous observons les nuages.",
    "feminine": "",
    "plural": "",
    "tense": "présent",
    "conjugation": "j’observe / tu observes / il observe / nous observons / vous observez / ils observent",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "comparer",
    "nature": "verbe",
    "definition": "Chercher les ressemblances et les différences.",
    "example": "Tu compares deux fractions.",
    "feminine": "",
    "plural": "",
    "tense": "présent",
    "conjugation": "je compare / tu compares / il compare / nous comparons / vous comparez / ils comparent",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "justifier",
    "nature": "verbe",
    "definition": "Donner une raison qui explique une réponse.",
    "example": "Je justifie mon choix.",
    "feminine": "",
    "plural": "",
    "tense": "présent",
    "conjugation": "je justifie / tu justifies / il justifie / nous justifions / vous justifiez / ils justifient",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "organiser",
    "nature": "verbe",
    "definition": "Préparer et mettre en ordre.",
    "example": "Nous organisons notre semaine.",
    "feminine": "",
    "plural": "",
    "tense": "présent",
    "conjugation": "j’organise / tu organises / il organise / nous organisons / vous organisez / ils organisent",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "vérifier",
    "nature": "verbe",
    "definition": "Contrôler si quelque chose est exact.",
    "example": "Vous vérifiez vos calculs.",
    "feminine": "",
    "plural": "",
    "tense": "présent",
    "conjugation": "je vérifie / tu vérifies / il vérifie / nous vérifions / vous vérifiez / ils vérifient",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "expliquer",
    "nature": "verbe",
    "definition": "Faire comprendre quelque chose.",
    "example": "Elle explique sa méthode.",
    "feminine": "",
    "plural": "",
    "tense": "présent",
    "conjugation": "j’explique / tu expliques / il explique / nous expliquons / vous expliquez / ils expliquent",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "choisir",
    "nature": "verbe",
    "definition": "Prendre une possibilité parmi plusieurs.",
    "example": "Nous choisissons un livre.",
    "feminine": "",
    "plural": "",
    "tense": "présent",
    "conjugation": "je choisis / tu choisis / il choisit / nous choisissons / vous choisissez / ils choisissent",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "réussir",
    "nature": "verbe",
    "definition": "Obtenir le résultat que l’on souhaitait.",
    "example": "Ils réussissent leur exercice.",
    "feminine": "",
    "plural": "",
    "tense": "présent",
    "conjugation": "je réussis / tu réussis / il réussit / nous réussissons / vous réussissez / ils réussissent",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "comprendre",
    "nature": "verbe",
    "definition": "Saisir le sens de quelque chose.",
    "example": "Tu comprends la consigne.",
    "feminine": "",
    "plural": "",
    "tense": "présent",
    "conjugation": "je comprends / tu comprends / il comprend / nous comprenons / vous comprenez / ils comprennent",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "apprendre",
    "nature": "verbe",
    "definition": "Acquérir une connaissance ou une compétence.",
    "example": "Nous apprenons de nouveaux mots.",
    "feminine": "",
    "plural": "",
    "tense": "présent",
    "conjugation": "j’apprends / tu apprends / il apprend / nous apprenons / vous apprenez / ils apprennent",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "écrire",
    "nature": "verbe",
    "definition": "Former des lettres pour exprimer des idées.",
    "example": "Vous écrivez un récit.",
    "feminine": "",
    "plural": "",
    "tense": "présent",
    "conjugation": "j’écris / tu écris / il écrit / nous écrivons / vous écrivez / ils écrivent",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  },
  {
    "word": "lire",
    "nature": "verbe",
    "definition": "Comprendre un texte écrit.",
    "example": "Elles lisent une histoire.",
    "feminine": "",
    "plural": "",
    "tense": "présent",
    "conjugation": "je lis / tu lis / il lit / nous lisons / vous lisez / ils lisent",
    "niveau": 2,
    "grade": "CM2",
    "source": "自主练习词 · 非老师指定词表"
  }
];
