(async function(){
const $=id=>document.getElementById(id);const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};const normalize=s=>s.normalize('NFC').trim().toLocaleLowerCase('fr').replace(/[’]/g,"'").replace(/\s+/g,' ');let words=[],selected=0;
await window.CM2Learning.ready;const state=window.CM2Learning.state;
for(const l of state.lists){const o=el('option',`${l.due_date} · ${l.title} · G${l.group_number}`);o.value=l.id;$('lists').append(o);}
$('list-status').textContent=state.publicOnly?'此处提供 CM2 自主练习。学校词表请进入下方受保护的学习空间。':!state.available?'学校词表暂时无法读取，请稍后刷新。自主练习仍可使用。':state.lists.length?'Les listes de la classe sont prêtes.':'还没有录入学校词表。这里先提供 CM2 自主练习。';
if(state.publicOnly){const a=el('a','进入学校词表 · 需要网站登录 →');a.href='https://tongtong-private-staging.euripscope.workers.dev/cm2_words.html';$('list-status').after(a);}
function speak(word){if(!('speechSynthesis'in window)){return false;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='fr-FR';u.rate=.8;speechSynthesis.speak(u);return true;}
function choose(){const list=state.lists.find(l=>l.id===$('lists').value);words=list?list.words:window.CM2_VOCABULARY;$('source').textContent=list?'老师布置 · 由家长录入。按单词本要求完成。':'自主练习词 · 由网站编写，不是老师本周布置。';selected=0;render();}
function render(){const buttons=$('words');buttons.hidden=false;buttons.replaceChildren();words.forEach((w,i)=>{const b=el('button',w.word);b.setAttribute('aria-pressed',String(i===selected));b.onclick=()=>{selected=i;render();};buttons.append(b);});const w=words[selected];const panel=$('atelier');panel.replaceChildren();if(!w){panel.append(el('p','Cette liste est vide.'));return;}
panel.append(el('span',w.nature||'Nature à vérifier dans le dictionnaire','tag'),el('h2',w.word),el('p',w.definition),el('p',w.example||'Invente une phrase avec ce mot.'));
const forms=[w.feminine&&'Féminin : '+w.feminine,w.plural&&'Pluriel : '+w.plural,w.conjugation&&(w.tense||'Conjugaison')+' : '+w.conjugation].filter(Boolean);if(forms.length)panel.append(el('div',forms.join('\n'),'forms'));
const listen=el('button','Écouter le mot 🔊');const audioStatus=el('p','','muted');listen.onclick=()=>{audioStatus.textContent=speak(w.word)?'Écoute, puis écris le mot sur ta feuille.':'La voix n’est pas disponible. Regarde, cache puis écris le mot.';};panel.append(listen,audioStatus);
const model=[...panel.children].filter(n=>n!==listen&&n!==audioStatus);const hide=el('button','Cacher le modèle · 遮住答案');hide.onclick=()=>{const hidden=!model[0].hidden;model.forEach(n=>n.hidden=hidden);$('words').hidden=hidden;hide.textContent=hidden?'Revoir le modèle · 再看一眼':'Cacher le modèle · 遮住答案';};panel.append(hide);
const exercise=el('select');exercise.id='exercise';const prompts=[['word','Écris le mot · 拼写',w.word],['nature','Quelle est sa nature ? · 词性',w.nature],['plural','Écris le pluriel · 复数',w.plural],['feminine','Écris le féminin · 阴性',w.feminine]].filter(x=>x[2]);for(const p of prompts){const o=el('option',p[1]);o.value=p[0];exercise.append(o);}const label=el('label','Mon petit défi');label.htmlFor='exercise';const answer=el('input');answer.id='answer';answer.autocomplete='off';answer.spellcheck=false;const alabel=el('label','Ma réponse');alabel.htmlFor='answer';const feedback=el('p','','feedback');feedback.setAttribute('role','status');const check=el('button','Vérifier');check.onclick=()=>{const expected=prompts.find(p=>p[0]===exercise.value)[2];feedback.textContent=!answer.value.trim()?'Écris une réponse avant de vérifier.':normalize(answer.value)===normalize(expected)?'Bravo ! Maintenant, utilise ce mot dans une phrase.':'Observe et réessaie : '+expected;};answer.onkeydown=e=>{if(e.key==='Enter')check.click();};exercise.onchange=()=>{answer.value='';feedback.textContent='';};panel.append(label,exercise,alabel,answer,check,feedback);
if(w.conjugation){const d=el('details');d.append(el('summary','Défi conjugaison · 收起答案，先在纸上完成'),el('p','Cache les formes ci-dessus et conjugue le verbe avec je, tu, il/elle, nous, vous, ils/elles. Vérifie ensuite chaque terminaison.'),el('p',w.conjugation));panel.append(d);}
const note=el('details');note.append(el('summary','Je relis comme en classe'),el('p','Je vérifie l’orthographe, les accents, les accords et les terminaisons. Je corrige en vert sur ma feuille.'));panel.append(note);
const actions=el('div',undefined,'actions');const prev=el('button','← Précédent');prev.disabled=selected===0;prev.onclick=()=>{selected--;render();};const next=el('button','Suivant →');next.disabled=selected===words.length-1;next.onclick=()=>{selected++;render();};actions.append(prev,el('span',`${selected+1} / ${words.length}`),next);panel.append(actions);
}
$('lists').onchange=choose;choose();
})();
